### ISSUE TITLE
Add your name to the contributors list

### ISSUE THREAD

**Issue by omarsar** [dair-ai/nlp_fundamentals#7]
Please say hi and add your name below if you wish to contribute to this project. Make sure to link your GitHub account so that I can add you to this project.

**Comment by e-tornike** [comment]
Hey, I'd like to contribute here!

**Comment by abdulrahimq** [comment]
Hello! I would like to contribute - Abed Qaddoumi

**Comment by shmuhammadd** [comment]
Hi, I would like to contribute.

**Comment by skeshaw** [comment]
Hey, I'd like to contribute here. - Keshaw

**Comment by sharan19** [comment]
Hi i am Sharan kumar. I would like to be part of NLP fundamentals.

**Comment by sudoberlin** [comment]
hello, I am Shubham Singh and I would like to be a part of this project!

**Comment by 12seetharaman** [comment]
Hi, I'd like to contribute here. - Ram

**Comment by dhruvagupta2014** [comment]
Hi I'd like to contribute to this project - Dhruv

**Comment by 12mohaned** [comment]
Hi I'd Like to contribute to this project -Mashaly

**Comment by AiswaryaSrinivas** [comment]
Hi, I would like to contribute to this Project - Aiswarya Ramachandran
